ISSUE_TEMPLATE/bug_report.md, ISSUE_TEMPLATE/bug_report.yml, ISSUE_TEMPLATE/config.yml, ISSUE_TEMPLATE/issue.md, ISSUE_TEMPLATE/issue.yml, README.md
closed #1 .
- #2 : Pull Request テンプレートの追加
=> #1: Create Issue Template

labeler.yml, workflows/labeler.yml
closed #7.
- 一旦choreのみ追加
- 別repoで実験を行う。バグがあれば適宜起票して対応する
=> feat: add labeler workflows (#7)

renovate.json
=> chore: renovate config

.github/workflows/issue.yml
=> feat: Add milestone for Issue (#24)

ISSUE_TEMPLATE/04-bug_report.yml
=> fix: Update 04-bug_report.yml

.github/workflows/issue.yml
=> fix: fix typo

ISSUE_TEMPLATE/02-Roadmap.yml, ISSUE_TEMPLATE/03-ADR.yml
=> docs: fix status dropdown

.github/workflows/renovate.yml
=> feat: add renovate validation workflow

.github/workflows/issue.yml
=> feat: Assign Issue author

pull_request_template.md
=> fix: fix PR tempalte

workflows /issue-milestone.yml
=> exp: add `workflows/issue-milestone.yml`

.github/workflows/issue.yml
=> refactor(temp): add if rule

.github/workflows/get-dates.yml
=> feat(temp): add Get dates flow

.github/workflows/get-dates.yml
=> fix(temp): fix description to get-dates flow

.github/workflows/issue.yml
=> chore: add parallel jobs

.github/workflows/pull_request.yml
=> fix(ci): add PR workflows

renovate.json5
- コメント追加のために`.json`から`.json5`に変更しました
=> Update and rename renovate.json to renovate.json5

.github/workflows/pull_request.yml
=> refactor: remove `strategy.matrix`

.github/workflows/get-month.yml
=> feat(ci): add get-month, get-today jobs

labels.yml
=> chore: add labels.yml

.github/workflows/sync-labels.yml
=> chore(ci): add label syncer workflow

.github/workflows/linter-eslint-using-reviewdog.yml
closed #58 .
- **reviewdog**を用いてPRにコメントします
=> feat(wf): add workflow for ESLint using reviewdog

.github/workflows/add-label-according-issue-title.yml
=> feat(wf): add workflow to add labels according to Issue title

.github/workflows/sync-labels.yml
=> refactor(ci): add `prune` option to labeler syncer workflow

.github/workflows/linter-eslint-using-reviewdog.yml
- ref: https://github.com/shinGangan/nuxt-nuxtui-templates/pull/95
=> refactor: Supports pnpm v10
